### ISSUE TITLE
Non-deterministic bug in deployment

### ISSUE THREAD

**Issue by chardetm** [BeyondTheClouds/juice#4]
Deployment with `database: galera` crashes with the message:

```
TASK [database : Start the MariaDB-Galera first container] ************************************************************************************************
Monday 27 August 2018  11:11:50 +0200 (0:00:01.076)       0:07:02.228 ********* 
fatal: [ecotype-8.nantes.grid5000.fr]: FAILED! => {"msg": "The conditional check 'inventory_hostname == dbmaster_node' failed. The error was: error while evaluating conditional (inventory_hostname == dbmaster_node): 'dbmaster_node' is undefined\n\nThe error appears to have been in '/home/mchardet/juice/ansible/roles/database/tasks/galera/deploy.yml': line 24, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Start the MariaDB-Galera first container\n  ^ here\n"}     
```

The corresponding line is this one:
https://github.com/BeyondTheClouds/juice/blob/3ffa37ba99f94bb74660d24d90b89158beeda887/ansible/roles/database/tasks/galera/deploy.yml#L46

The error seems to be that `dbmaster_node` is undefined, and I actually couldn't find any mention of `dbmaster_node` anywhere in the code.

**Comment by chardetm** [comment]
Title changed, actually it seems like this error is non-deterministic: I tried to deploy with `database: mariadb` again (it was working before), and this time it crashed with message:

```
TASK [database : Waiting for MariaDB to be ready] *********************************************************************************************************
Monday 27 August 2018  11:58:45 +0200 (0:00:08.526)       0:07:22.252 ********* 
fatal: [ecotype-46.nantes.grid5000.fr]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dbmaster_node' is undefined\n\nThe error appears to have been in '/home/mchardet/juice/ansible/roles/database/tasks/mariadb/deploy.yml': line 29, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Waiting for MariaDB to be ready\n  ^ here\n"}         
        to retry, use: --limit @/home/mchardet/juice/ansible/scaffolding.retry
```

The corresponding line being:
https://github.com/BeyondTheClouds/juice/blob/3ffa37ba99f94bb74660d24d90b89158beeda887/ansible/roles/database/tasks/mariadb/deploy.yml#L31

**Comment by rcherrueau** [comment]
The `db_master_node` is defined in the `ansible/group_vars/all.yml`. This is the common place for Ansible projects to define global settings. See:
https://github.com/BeyondTheClouds/juice/blob/3ffa37ba99f94bb74660d24d90b89158beeda887/ansible/group_vars/all.yml#L1

Old version of enoslib did not load this automatically, but has been fixed in https://github.com/BeyondTheClouds/enoslib/commit/789d4631cd00d96334dd224c94776d4a8c04100f. I recommend to drop your current venv and reinstall juice.
